version: '3'
services:
  pgdb:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        -./pgdata:/var/lib/postgresql/data/pgdata
