name: 'Nest Actions'
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        using: 'node20'
        main: 'main.js'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test