name: 'Nest Actions'
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    strategy:
      matrix:
        version: [18,20]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          node-version: ${{matrix.version}}
      - name: Install deps
        run: npm ci
      - name: Run test
        run: npm run test
  secret:
    runs-on: ubuntu-latest
    steps:
     - name: Print secret
       run: echo ${{secrets.NEST_ACTIONS_VERSION}}